export enum Notification {
  ADD_CARD_USER = 'add cards',
  REMOVE_CARD_USER = 'remove cards',
  CREATE_TRANSACTION = 'create transactions',
  TRANSFER_TRANSACTION = 'transfer transactions',
  CREATE_SHOP = 'create shops',
  CREATE_PRODUCT = 'create products',
  END_PRODUCT = 'end products',
  CREATE_PURCHASE = 'create purchases',
  CREATE_LOCKER = 'create lockers',
  CREATE_ORDER = 'create orders',
  TAKE_ORDER = 'take orders',
  CANCEL_ORDER = 'cancel orders',
  EXECUTE_ORDER = 'execute orders',
  COMPLETE_ORDER = 'complete orders',
}
