export enum CardError {
  NON_ZERO_BALANCE = 'Ненулевой баланс на карте',
  HAS_USER = 'Карта имеет общего игрока',
  HAS_FINE = 'Карта имеет активный штраф',
  HAS_MARKET = 'Карта имеет активный рынок',
  HAS_SHOP = 'Карта имеет активный магазин',
  HAS_ORDER = 'Карта имеет активный заказ',
  USER_ALREADY_IN = 'Игрок уже в карте',
  USER_NOT_IN = 'Игрок не в карте',
  USER_IS_OWNER = 'Игрок является владельцем карты',
  NOT_ENOUGH_BALANCE = 'Недостаточный баланс на карте',
  NOT_OWNER = 'Вы не владелец карты',
  NOT_USER = 'Вы не участник карты',
  NOT_FOUND = 'Не удалось найти карту',
  CREATE_FAILED = 'Не удалось создать карту',
  EDIT_FAILED = 'Не удалось редактировать карту',
  DELETE_FAILED = 'Не удалось удалить карту',
  ADD_USER_FAILED = 'Не удалось добавить игрока',
  REMOVE_USER_FAILED = 'Не удалось убрать игрока',
  INCREASE_BALANCE_FAILED = 'Не удалось увеличить баланс карты',
  DECREASE_BALANCE_FAILED = 'Не удалось уменьшить баланс карты',
}
