export enum OrderError {
  ALREADY_TAKEN = 'Заказ уже взято',
  NOT_TAKEN = 'Заказ не взято',
  ALREADY_EXECUTED = 'Заказ уже выполнено',
  NOT_EXECUTED = 'Заказ не выполнено',
  ALREADY_COMPLETED = 'Заказ уже завершено',
  NOT_CUSTOMER = 'Вы не заказчик заказа',
  NOT_EXECUTOR = 'Вы не исполнитель заказа',
  NOT_FOUND = 'Не удалось найти заказ',
  CREATE_FAILED = 'Не удалось создать заказ',
  EDIT_FAILED = 'Не удалось редактировать заказ',
  DELETE_FAILED = 'Не удалось удалить заказ',
  TAKE_FAILED = 'Не удалось взять заказ',
  CANCEL_FAILED = 'Не удалось отменить заказ',
  EXECUTE_FAILED = 'Не удалось выполнить заказ',
  COMPLETE_FAILED = 'Не удалось завершить заказ',
}
