export enum UserError {
  NICK_ALREADY_USED = 'Игрок с таким ником уже существует',
  INVALID_PASSWORD = 'Неправильный пароль',
  ALREADY_HAVE_ROLE = 'Игрок уже имеет роль',
  NOT_HAVE_ROLE = 'Игрок не имеет роли',
  NOT_FOUND = 'Не удалось найти игрока',
  CREATE_FAILED = 'Не удалось создать игрока',
  SET_TOKEN_FAILED = 'Не удалось установить токен игрока',
  RESET_TOKEN_FAILED = 'Не удалось сбросить токен игрока',
  EDIT_PROFILE_FAILED = 'Не удалось редактировать профиль игрока',
  CHANGE_PASSWORD_FAILED = 'Не удалось изменить пароль игрока',
  ADD_ROLE_FAILED = 'Не удалось добавить роль игрока',
  REMOVE_ROLE_FAILED = 'Не удалось убрать роль игрока',
  SET_ONLINE_FAILED = 'Не удалось установить онлайн игрока',
  RESET_ONLINE_FAILED = 'Не удалось сбросить онлайн игрока',
}
